### ISSUE TITLE
cannot run ruhoh

### ISSUE THREAD

**Issue by rlemon** [ruhoh/ruhoh.js#3]
Here is the error i'm getting (after following the instructions [here](http://ruhoh.com/usage/)): 

```
$ gem install ruhoh
Successfully installed ruhoh-0.2.1
1 gem installed
Installing ri documentation for ruhoh-0.2.1...
Installing RDoc documentation for ruhoh-0.2.1...
$ ruhoh help
/home/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- kramdown (LoadError)
    from /home/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/user/.rvm/gems/ruby-1.9.3-p194/gems/ruhoh-0.2.1/lib/ruhoh/converters/converter.rb:1:in `<top (required)>'
    from /home/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/user/.rvm/gems/ruby-1.9.3-p194/gems/ruhoh-0.2.1/lib/ruhoh.rb:27:in `<top (required)>'
    from /home/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/user/.rvm/gems/ruby-1.9.3-p194/gems/ruhoh-0.2.1/bin/ruhoh:5:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-1.9.3-p194/bin/ruhoh:19:in `load'
    from /home/user/.rvm/gems/ruby-1.9.3-p194/bin/ruhoh:19:in `<main>'
```

**Comment by plusjade** [comment]
@rlemon this is an oversight on my part. It seems ruhoh is requiring kramdown but my repo says maruku (no idea what's causing that)

As a quick fix, until I push 0.2.2 (next couple of days) you can simply install the kramdown gem:

``` bash
$ gem install kramdown
```

That should do it! Let me know if you are able to run it.
